### ISSUE TITLE
test.py Runtime Error

### ISSUE THREAD

**Issue by ChaejinE** [maudzung/Complex-YOLOv4-Pytorch#38]
```shell
Traceback (most recent call last):
  File "test.py", line 98, in <module>
    model.load_state_dict(torch.load(configs.pretrained_path))
  File "/home/chaejin/anaconda3/envs/complex-yolov4/lib/python3.8/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/chaejin/anaconda3/envs/complex-yolov4/lib/python3.8/site-packages/torch/serialization.py", line 773, in _legacy_load
    result = unpickler.load()
  File "/home/chaejin/anaconda3/envs/complex-yolov4/lib/python3.8/site-packages/torch/serialization.py", line 729, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/chaejin/anaconda3/envs/complex-yolov4/lib/python3.8/site-packages/torch/serialization.py", line 178, in default_restore_location
    result = fn(storage, location)
  File "/home/chaejin/anaconda3/envs/complex-yolov4/lib/python3.8/site-packages/torch/serialization.py", line 154, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/chaejin/anaconda3/envs/complex-yolov4/lib/python3.8/site-packages/torch/serialization.py", line 144, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on CUDA device '
RuntimeError: Attempting to deserialize object on CUDA device 2 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.
```
I got this Runtime Error.

![image](https://user-images.githubusercontent.com/69780812/144972458-a8209b65-f18a-4ff2-b68c-d7229117cd8a.png)
Nvidia GPU was operating well,,
I don't know why this program was not operated
Please test or review this program..

**Comment by ChaejinE** [comment]
Well, Should I use multi gpu ?

**Comment by ChaejinE** [comment]
#8 
This issue helps me know execute test.py
but, i didn't execute yolov4 version.
It don't operate yet?

**Comment by SinDongHwan** [comment]
Hi, @ChaejinE.
When call torch.load(), use a parameter(map_location).
example code
```
configs.device = torch.device('cpu' if configs.no_cuda else 'cuda:{}'.format(configs.gpu_idx))
model.load_state_dict(torch.load(configs.pretrained_path, map_location=configs.device))
```

Good Luck.

torch.load 함수 호출하실 때, map_location 파라미터를 사용하세요.
map_location 파라미터를 사용하지 않을 경우, device 정보를 pre-trained model에 적힌 것을 읽어옵니다.
